# operations at cursors #2
L = '\\\\\\\\'

keys('\<C-Down>wwD\<Esc>')
keys('jj^\<C-Down>C')
keys('\<C-v>')
keys('\<C-w>')
keys('\<C-w>')
keys('\<Esc>Bba')
keys('\<C-w>')
keys('\<C-w>')
keys('\<C-w>')
keys('\<Esc>')
keys('\<Esc>')

keys('jj^')
keys(L+'/c..')
keys('\<CR>')
keys('n'+L+'n')
keys(' ')
keys('\<CR>')
keys('\<Esc>')

keys('jj^\<C-Down>fd')
keys('sEE~o\<Tab>wC')
keys('ciao')
keys('\<Esc>')
keys('\<Esc>')

keys('jj0$h')
keys('\<C-Down>\<C-Down>9h')
keys('c2E')
keys(' c2E')
keys('\<Esc>')
keys('\<Esc>')
