# operations at cursors #2

keys(r'\<C-Down>wwD\<Esc>')
keys(r'jj^\<C-Down>C')
keys(r'\<C-v>')
keys(r'\<C-w>')
keys(r'\<C-w>')
keys(r'\<Esc>Bba')
keys(r'\<C-w>')
keys(r'\<C-w>')
keys(r'\<C-w>')
keys(r'\<Esc>')
keys(r'\<Esc>')

keys(r'jj^')
keys(r'\\\\/c..')
keys(r'\<CR>')
keys(r'n\\\\n')
keys(r' ')
keys(r'\<CR>')
keys(r'\<Esc>')

keys(r'jj^\<C-Down>fd')
keys(r'sEE~o\<Tab>wC')
keys(r'ciao')
keys(r'\<Esc>')
keys(r'\<Esc>')

keys(r'jj0$h')
keys(r'\<C-Down>\<C-Down>9h')
keys(r'c2E')
keys(r' c2E')
keys(r'\<Esc>')
keys(r'\<Esc>')
