# dot/select operator si'
keys(r'\<C-n>\<C-n>\<C-n>\<C-n>')
keys(r'c')
keys(r'changed_word')
keys(r'\<Esc>')
keys(r'\<Esc>')
keys(r'ggA\<Tab>')
keys(r'text')
keys(r'\<Esc>')
keys(r'0j\<C-Down>\<C-Down>')
keys(r'.')
keys(r'0dw.~...')
keys(r'\<Esc>')

keys(r"6Gf'l")
keys(r'\<C-n>\<C-n>')
keys(r"si'")
keys(r'c')
keys(r'change')
