# various change commands
L = '\\\\\\\\'

keys(':set tw=79\<CR>')
keys(':set autoindent\<CR>')
keys('2\<C-Down>')
keys('I')
keys('back_delete_test\<C-w>')
keys('\<Esc>')
keys('gciw')
keys('smart case')
keys('\<Esc>')
keys('ea')
keys('_text')
keys('\<Esc>')
keys('wTxcT_')
keys('TEX')
keys('\<Esc>')
keys('f(gcib')
keys('gcib')
keys('\<Esc>')
keys('\<Esc>}j$2\<C-Down>ciw')
keys('CIW')
keys('\<Esc>')
keys('\<Esc>j2\<C-Down>')
keys('c$')
keys('_c$')
keys('\<Esc>')
keys('\<Esc>j03\<C-Down>')
keys('cc')
keys('keep indent please')
keys('\<Esc>')
keys('\<Esc>gg0')
keys('2\<C-Down>wcl')
keys('C')
keys('\<Esc>')
keys('$h2cl')
keys('2CL')
keys('\<Esc>')
keys('\<Esc>')
