# various change commands

keys(r':set tw=79\<CR>')
keys(r':set autoindent\<CR>')
keys(r'2\<C-Down>')
keys(r'I')
keys(r'back_delete_test\<C-w>')
keys(r'\<Esc>')
keys(r'gciw')
keys(r'smart case')
keys(r'\<Esc>')
keys(r'ea')
keys(r'_text')
keys(r'\<Esc>')
keys(r'wTxcT_')
keys(r'TEX')
keys(r'\<Esc>')
keys(r'f(gcib')
keys(r'gcib')
keys(r'\<Esc>')
keys(r'\<Esc>}j$2\<C-Down>ciw')
keys(r'CIW')
keys(r'\<Esc>')
keys(r'\<Esc>j2\<C-Down>')
keys(r'c$')
keys(r'_c$')
keys(r'\<Esc>')
keys(r'\<Esc>j03\<C-Down>')
keys(r'cc')
keys(r'keep indent please')
keys(r'\<Esc>')
keys(r'\<Esc>gg0')
keys(r'2\<C-Down>wcl')
keys(r'C')
keys(r'\<Esc>')
keys(r'$h2cl')
keys(r'2CL')
keys(r'\<Esc>')
keys(r'\<Esc>')
