# change commands #2
keys(r'2\<C-Down>')
keys(r'f(')
keys(r'gcib')
keys(r'gcib')
keys(r'\<Esc>')
keys(r'\<Esc>')
keys(r'gg0$')
keys(r'\<C-N>\<C-N>')
keys(r'\<Tab>')
keys(r'\<C-Down>')
keys(r'$ciw')
keys(r'CIW')
keys(r'\<Esc>')
keys(r'bbb')
keys(r'c2aw')
keys(r'c2aw ')
keys(r'\<Esc>')
